// Google Flow's new (Sep 2026) frontend is an Angular app that talks to its
// backend exclusively through the classic "batchexecute" RPC transport
// (the same wire protocol Gmail/Docs/Photos use internally) — NOT the old
// aisandbox-pa.googleapis.com REST + Bearer-token API this worker was
// originally built against. That old API is gone: zero requests to
// aisandbox-pa appear anywhere in a live capture of the current site.
//
// Reverse-engineered from a real HAR capture (Sep 2026) of flow.google.com.
// Reference rpcids observed:
//   ogiZ0b — generate image
//   MZZa6b — generate video
//   jwpduf — poll media status by id (returns "Media not found" while pending)
//   as29s  — fetch one media's full details incl. signed download URL
//   ngNC2  — fetch one project's details by resource name
// Every one of the above shares the same outer request/response envelope,
// which is what this module implements generically.

import type { Page } from 'puppeteer-core';
import { LABS_BASE } from './constants.js';

const BATCHEXEC_PATH = '/_/AiSandboxAngularFrontend/data/batchexecute';

export interface BatchExecSession {
  bl: string;
  sid: string;
  at: string;
}

/**
 * bl / f.sid / at (the anti-XSRF token, mirrors the classic Google
 * "SNlM0e" token) are generated by Google's own client JS at page load —
 * we have no independent way to derive them. Instead of reverse-engineering
 * that generation, just listen for the next request the SPA itself fires
 * to batchexecute (telemetry pings fire within ~1s of any page load) and
 * copy its session params. Cheap, robust to Google changing the token
 * format again later.
 */
export function captureSession(page: Page, timeoutMs = 20_000): Promise<BatchExecSession> {
  return new Promise((resolve, reject) => {
    let done = false;
    const handler = (req: any) => {
      if (done) return;
      const url: string = req.url();
      if (!url.includes(BATCHEXEC_PATH)) return;
      try {
        const u = new URL(url);
        const bl = u.searchParams.get('bl');
        const sid = u.searchParams.get('f.sid');
        const body: string = req.postData() || '';
        const m = body.match(/(?:^|&)at=([^&]+)/);
        if (bl && sid && m) {
          done = true;
          clearTimeout(timer);
          page.off('request', handler);
          resolve({ bl, sid, at: decodeURIComponent(m[1]) });
        }
      } catch {
        // keep waiting for a well-formed request
      }
    };
    const timer = setTimeout(() => {
      if (done) return;
      done = true;
      page.off('request', handler);
      // Cheap enough to always include — this is the one piece of context
      // that actually explains a timeout (stuck on marketing/login page vs.
      // a real project page that just never fired a request in time).
      reject(
        new Error(
          `captureSession: timed out waiting for a batchexecute request (page.url()=${page.url()})`,
        ),
      );
    }, timeoutMs);
    page.on('request', handler);
  });
}

// Real captures show _reqid jumping by ~100-300 between consecutive calls
// in the same tab, starting from a per-session base in the low millions —
// looks like a monotonic counter seeded per page load, not validated
// strictly server-side. A random base + steady increment matches the
// pattern closely enough.
let _reqCounter = Math.floor(Math.random() * 900_000) + 100_000;
function nextReqId(): number {
  _reqCounter += 100;
  return _reqCounter;
}

function batchExecuteUrl(session: BatchExecSession, rpcid: string, sourcePath: string): string {
  const p = new URLSearchParams({
    rpcids: rpcid,
    'source-path': sourcePath,
    bl: session.bl,
    'f.sid': session.sid,
    hl: 'vi',
    _reqid: String(nextReqId()),
    rt: 'c',
  });
  return `${LABS_BASE}${BATCHEXEC_PATH}?${p.toString()}`;
}

function batchExecuteBody(rpcid: string, argsJson: string, session: BatchExecSession): string {
  const inner = JSON.stringify([[[rpcid, argsJson, null, 'generic']]]);
  return `f.req=${encodeURIComponent(inner)}&at=${encodeURIComponent(session.at)}&`;
}

/**
 * Parse a batchexecute response stream:
 *   )]}'
 *   <blank>
 *   <byte-length>
 *   [["wrb.fr","<rpcid>","<json-encoded-string>",...], ...]
 *   <byte-length>
 *   [["e",4,null,null,<n>]]           <- trailing end-of-stream marker
 * Real payloads escape embedded newlines as `\n` inside the JSON string,
 * so splitting the raw frame on literal `\n` is safe — those only ever
 * appear between frames, never inside one.
 */
export function parseBatchExecuteResponse(text: string, rpcid: string): unknown {
  const body = text.replace(/^\)\]\}'\r?\n?/, '');
  const lines = body.split('\n').filter((l) => l.trim().length > 0);
  for (const line of lines) {
    if (/^\d+$/.test(line.trim())) continue; // byte-length marker line
    let frame: unknown;
    try {
      frame = JSON.parse(line);
    } catch {
      continue;
    }
    if (!Array.isArray(frame)) continue;
    for (const entry of frame as unknown[]) {
      if (!Array.isArray(entry) || entry[0] !== 'wrb.fr' || entry[1] !== rpcid) continue;
      if (typeof entry[2] === 'string') {
        try {
          return JSON.parse(entry[2] as string);
        } catch {
          return entry[2];
        }
      }
      // entry[2] is null on an RPC-level error — the status code (gRPC-style,
      // e.g. 5 = NOT_FOUND) rides in entry[5] as [code] instead.
      const code = Array.isArray(entry[5]) ? (entry[5] as unknown[])[0] : undefined;
      throw new Error(`batchexecute ${rpcid}: RPC error, code=${code ?? 'unknown'} — raw: ${line.slice(0, 300)}`);
    }
  }
  throw new Error(`parseBatchExecuteResponse: no frame for rpcid=${rpcid} in: ${text.slice(0, 300)}`);
}

/**
 * Fire one batchexecute call from inside the page (so it rides the page's
 * own cookies + CORS same-origin context) and return the parsed payload
 * for `rpcid`.
 */
export async function callBatchExecute(
  page: Page,
  session: BatchExecSession,
  rpcid: string,
  argsJson: string,
  sourcePath: string,
): Promise<unknown> {
  const url = batchExecuteUrl(session, rpcid, sourcePath);
  const body = batchExecuteBody(rpcid, argsJson, session);
  const result = await page.evaluate(
    async (u: string, b: string) => {
      try {
        const res = await fetch(u, {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },
          body: b,
          credentials: 'include',
        });
        return { status: res.status, text: await res.text() };
      } catch (e: any) {
        return { status: 0, text: String(e?.message ?? e) };
      }
    },
    url,
    body,
  );
  if (result.status < 200 || result.status >= 300) {
    throw new Error(`callBatchExecute ${rpcid}: HTTP ${result.status}: ${result.text.slice(0, 300)}`);
  }
  return parseBatchExecuteResponse(result.text, rpcid);
}
